import {createHash} from 'node:crypto';
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';

// Pin the Google-reviewed v3 source. Changed input requires another review.
export const reviewedCandidateHash = 'c9e277d3eb644ad6c1d5543dd405cdfd511ea1ca659b7f97b278f715115168ff';
export function buildProductionSource(input) {
  if (createHash('sha256').update(input).digest('hex') !== reviewedCandidateHash) throw new Error('Candidate changed: review before producing a production bundle.');
  const changes = [
    ["var ND_SCHEMA = 'nodina-contact-file-v1';", "var ND_SCHEMA = 'nodina-production-contact-file-v1';"],
    ["p.getProperty('ND_MODE') !== 'rehearsal'", "p.getProperty('ND_MODE') !== 'production'"],
    ["if (!validation.ok || !/^TEST-/i.test(validation.data.name))", "if (!validation.ok)"],
    ['function ndInitializeRehearsal_()', 'function ndInitializeProduction_()'],
    ['NODINA — RECETTE — Dossiers individuels', 'NODINA — Dossiers individuels'],
    ['NODINA — RECETTE — Synthèse des comptes', 'NODINA — Synthèse des comptes'],
    ["'Recette privée : utilisez uniquement des données fictives et un nom commençant par TEST-.'", "'Ces informations servent à traiter votre demande. Ne transmettez pas de données confidentielles.'"],
    ["'Private rehearsal: use fictional data only and a name starting with TEST-.'", "'This information is used to handle your inquiry. Do not include confidential information.'"],
    ['/* Offline-tested candidate.', '/* Production preparation, not deployed.'],
    ['// This isolated candidate accepts TEST- submissions only; never prefill PII.', '// Production profile; never prefill personal information.'],
    ['// Editor only. Run only after JD approves creating the isolated test storage.', '// Editor only. Initialize a separate private production store after review.'],
  ];
  let output = input;
  for (const [before, after] of changes) {
    if (output.split(before).length !== 2) throw new Error('Ambiguous production transformation.');
    output = output.replace(before, after);
  }
  return '// GENERATED by tools/forms/production/build.mjs; no credentials or deployment.\n' + output;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.length !== 3) throw new Error('Usage: node tools/forms/production/build.mjs OUTPUT.gs');
  const input = ['core.gs','google.gs','web.gs'].map(name => readFileSync(new URL('../candidate/' + name,import.meta.url),'utf8')).join('\n');
  const output = buildProductionSource(input);
  writeFileSync(process.argv[2], output);
  console.log('Prepared production source; SHA-256 ' + createHash('sha256').update(output).digest('hex'));
}
