// GENERATED by tools/forms/production/build.mjs; no credentials or deployment.
/* Production preparation, not deployed. No Google calls here. All editor-only helpers end
 * in underscore so google.script.run cannot invoke them. Never load v1 with it. */
var ND_SCHEMA = 'nodina-production-contact-file-v1';
var ND_HEADERS = ['timestamp', 'request_id', 'ref', 'locale', 'name', 'email', 'organization', 'offer', 'project', 'timing', 'consent_text', 'consent_version', 'consent_timestamp', 'utm_source', 'utm_medium', 'utm_campaign', 'notification_status'];
var ND_CONSENT = {fr: 'J’accepte que NODINA utilise ces informations pour répondre à ma demande.', en: 'I agree that NODINA may use this information to respond to my inquiry.'};
var ND_UUID = /^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;

function ndEqual_(a, b) {
  a = String(a); b = String(b);
  var difference = a.length ^ b.length;
  for (var i = 0; i < Math.max(a.length, b.length); i++) difference |= (a.charCodeAt(i) || 0) ^ (b.charCodeAt(i) || 0);
  return difference === 0;
}

function ndIssue_(locale, now, ttl, crypto) {
  if (['fr', 'en'].indexOf(locale) < 0 || !Number.isInteger(ttl) || ttl < 60 || ttl > 86400) throw new Error('configuration');
  var id = crypto.uuid().toLowerCase();
  if (!ND_UUID.test(id)) throw new Error('configuration');
  var issued = Math.floor(now / 1000), expires = issued + ttl;
  var body = ['v1', id, issued, expires, locale].join('.');
  return {token: body + '.' + crypto.sign(body), request_id: id, expires_at: new Date(expires * 1000).toISOString()};
}

function ndVerify_(token, locale, now, crypto) {
  var parts = typeof token === 'string' && token.length <= 220 ? token.split('.') : [];
  if (parts.length !== 6 || parts[0] !== 'v1' || !ND_UUID.test(parts[1]) || parts[4] !== locale || !/^[A-Za-z0-9_-]{43}$/.test(parts[5])) return null;
  if (!/^\d{10}$/.test(parts[2]) || !/^\d{10}$/.test(parts[3])) return null;
  var issued = Number(parts[2]), expires = Number(parts[3]), seconds = Math.floor(now / 1000);
  if (issued > seconds || expires <= seconds || expires - issued < 60 || expires - issued > 86400) return null;
  if (!ndEqual_(parts[5], crypto.sign(parts.slice(0, 5).join('.')))) return null;
  return {id: parts[1], issued: issued, expires: expires, locale: locale};
}

function ndValidate_(p, now, crypto) {
  p = p || {};
  var claim = ndVerify_(p.receipt_token, p.locale, now, crypto);
  if (!claim || p.request_id !== claim.id || String(p.website || '').trim()) return {ok: false, code: 'invalid'};
  var data = {}, limits = {name: 120, email: 254, organization: 160, project: 5000, timing: 200};
  for (var key in limits) {
    var value = String(p[key] || '').trim();
    if (value.length > limits[key] || /[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/.test(value)) return {ok: false, code: 'invalid'};
    data[key] = value;
  }
  if (!data.name || !data.organization || data.project.length < 10 || !/^[^\s@,;<>]+@[^\s@,;<>]+\.[^\s@,;<>]+$/.test(data.email) || /[\r\n]/.test(data.name + data.email + data.organization)) return {ok: false, code: 'invalid'};
  if (p.consent !== 'yes' || p.consent_version !== 'contact-v1' || ['unknown', 'teams', 'systems', 'combined'].indexOf(p.offer) < 0) return {ok: false, code: 'invalid'};
  if (p.started_at) {
    var elapsed = now - Number(p.started_at);
    if (!isFinite(elapsed) || elapsed < 1500 || elapsed > 86400000) return {ok: false, code: 'invalid'};
  }
  data.request_id = claim.id; data.locale = p.locale; data.offer = p.offer;
  data.ref = /^\/(fr|en)(\/[a-z0-9-]+)*\/$/.test(p.ref || '') ? p.ref : '/' + p.locale + '/contact/';
  ['utm_source', 'utm_medium', 'utm_campaign'].forEach(function (key) { data[key] = String(p[key] || '').replace(/[\x00-\x1f\x7f]/g, '').slice(0, 100); });
  return {ok: true, data: data, claim: claim};
}

function ndPayloadHash_(data, crypto) {
  return crypto.sign(JSON.stringify(['payload-v1', data.ref, data.locale, data.name, data.email, data.organization, data.offer, data.project, data.timing, 'contact-v1', data.utm_source, data.utm_medium, data.utm_campaign]));
}

function ndRow_(data, timestamp) {
  // Adapters write RAW strings, including formula-looking text. Never USER_ENTERED.
  return [timestamp, data.request_id, data.ref, data.locale, data.name, data.email, data.organization, data.offer, data.project, data.timing, ND_CONSENT[data.locale], 'contact-v1', timestamp, data.utm_source, data.utm_medium, data.utm_campaign, 'pending'];
}

function ndRecord_(validation, d) {
  if (!validation.ok) return validation;
  var data = validation.data, claim = validation.claim, hash = ndPayloadHash_(data, d.crypto);
  var op = d.getOp(claim.id);
  if (op && op.kind === 'retired') return {ok: false, code: 'invalid'};
  if (op && (op.hash !== hash || op.expires !== claim.expires)) return {ok: false, code: 'invalid'};
  var matches = d.find(claim.id);
  if (matches.length > 1) throw new Error('ambiguous');
  var file = matches[0];
  if (!file && op && op.fileId) file = d.getFile(op.fileId);
  if (!file && op) throw new Error('creation uncertain');
  if (!file) {
    d.invalidate();
    op = {kind: 'creating', hash: hash, expires: claim.expires, timestamp: new Date(d.now()).toISOString()};
    d.putOp(claim.id, op); // Durable before the non-idempotent Sheets creation.
    file = d.create({id: claim.id, hash: hash, issued: claim.issued, expires: claim.expires, timestamp: op.timestamp});
    op.fileId = file.id; d.putOp(claim.id, op);
  }
  d.assertFile(file, claim, file.hash);
  if (file.hash !== hash) return {ok: false, code: 'invalid'};
  if (file.trashed) return {ok: false, code: 'invalid'};
  if (file.state !== 'complete') {
    d.invalidate();
    var row = ndRow_(data, file.timestamp);
    d.write(file, row);
    if (JSON.stringify(d.readRow(file)) !== JSON.stringify(row)) throw new Error('readback');
    d.complete(file); file.state = 'complete';
  } else {
    // Verify the receipt still contains the acknowledged content, not a stale flag.
    var saved = d.readRow(file), expected = ndRow_(data, file.timestamp);
    if (!Array.isArray(saved) || saved.length !== ND_HEADERS.length || JSON.stringify(saved.slice(0, 16)) !== JSON.stringify(expected.slice(0, 16))) throw new Error('receipt changed');
  }
  var status = d.readStatus(file);
  if (['pending', 'sent', 'failed', 'unknown'].indexOf(status) < 0) throw new Error('notification state');
  if (status === 'pending') {
    // Persist unknown BEFORE MailApp. A timeout cannot cause a second send.
    d.mark(file, 'unknown');
    try {
      if (!d.canNotify()) d.mark(file, 'failed');
      else {
        d.notify({subject: 'NODINA · Nouvelle demande', body: 'Référence : ' + claim.id + '\n\nDossier privé : https://docs.google.com/spreadsheets/d/' + file.id + '/edit'});
        d.mark(file, 'sent');
      }
    } catch (error) { /* unknown is intentionally retained; no automatic resend */ }
  }
  d.removeOp(claim.id);
  return {ok: true};
}

function ndRetire_(file, expectedId, d) {
  // Preparation only: never deletes a file. Caller owns the lock and approval.
  if (!ND_UUID.test(expectedId) || file.requestId !== expectedId || file.state !== 'complete' || file.trashed) throw new Error('scope');
  d.assertRetirementFile(file);
  d.invalidate();
  if (file.expires * 1000 > d.now()) d.putOp(expectedId, {kind: 'retired', expires: file.expires});
  else d.removeOp(expectedId);
  return {prepared: true, temporary_until: new Date(file.expires * 1000).toISOString()};
}

function ndCounts_(files, d) {
  var seen = {}, buckets = {};
  files.forEach(function (file) {
    if (seen[file.requestId]) throw new Error('duplicate reference');
    seen[file.requestId] = true;
    if (file.state !== 'complete' || file.trashed || d.isRetired(file.requestId)) throw new Error('incomplete coverage');
    d.assertRetirementFile(file);
    var row = d.readMetrics(file);
    if (!row || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(row.timestamp) || !Number.isFinite(Date.parse(row.timestamp)) || new Date(row.timestamp).toISOString() !== row.timestamp || !/^\/(fr|en)(\/[a-z0-9-]+)*\/$/.test(row.ref)) throw new Error('metrics schema');
    if (/^TEST-/i.test(row.name) || /^TEST-/i.test(row.ref)) return;
    var day = d.day(row.timestamp), key = day + '|' + row.ref;
    if (!buckets[key]) buckets[key] = [day, row.ref, 0];
    buckets[key][2]++;
  });
  return Object.keys(buckets).sort().map(function (key) { return buckets[key]; });
}

/* Google adapter: Advanced Drive v3 and Sheets v4, drive.file only.
 * No DriveApp, SpreadsheetApp, Gmail read/write, or deletion endpoint. */
function ndSettings_(needsFiles) {
  var p = PropertiesService.getScriptProperties();
  var ttl = Number(p.getProperty('ND_TOKEN_TTL_SECONDS'));
  var owner = p.getProperty('ND_OWNER_EMAIL');
  if (p.getProperty('ND_MODE') !== 'production' || !Number.isInteger(ttl) || ttl < 60 || ttl > 86400 || !/^[^\s@,;<>]+@[^\s@,;<>]+\.[^\s@,;<>]+$/.test(owner || '')) throw new Error('configuration');
  var cfg = {properties: p, owner: owner, recipient: owner, ttl: ttl, folderId: p.getProperty('ND_FOLDER_ID'), summaryId: p.getProperty('ND_SUMMARY_ID'), key: p.getProperty('ND_SIGNING_KEY')};
  if (needsFiles && (!cfg.folderId || !cfg.summaryId || !cfg.key || cfg.key.length < 64)) throw new Error('configuration');
  return cfg;
}

function ndCrypto_(cfg) {
  return {uuid: function () { return Utilities.getUuid(); }, sign: function (text) {
    return Utilities.base64EncodeWebSafe(Utilities.computeHmacSha256Signature(text, cfg.key, Utilities.Charset.UTF_8)).replace(/=+$/, '');
  }};
}

function ndAllPages_(fetch) {
  var result = [], page, token, seen = {};
  do {
    page = fetch(token);
    if (!page || page.incompleteSearch) throw new Error('coverage');
    result = result.concat(page.items || []);
    if (result.length > 1000) throw new Error('limit');
    token = page.nextPageToken;
    if (token && seen[token]) throw new Error('pagination');
    if (token) seen[token] = true;
  } while (token);
  return result;
}

function ndFile_(id) {
  var f = Drive.Files.get(id, {fields: 'id,name,mimeType,parents,trashed,driveId,modifiedTime,owners(emailAddress),appProperties'});
  var a = f.appProperties || {};
  return {id: f.id, name: f.name, mimeType: f.mimeType, parents: f.parents || [], trashed: !!f.trashed, driveId: f.driveId, owners: f.owners || [], modifiedTime: f.modifiedTime, schema: a.nd_schema, kind: a.nd_kind, requestId: a.request_id, hash: a.payload_hash, state: a.receipt_state, timestamp: a.received_at, issued: Number(a.issued), expires: Number(a.expires)};
}

function ndPrivate_(file, cfg) {
  if (file.driveId || file.owners.length !== 1 || file.owners[0].emailAddress !== cfg.owner) throw new Error('owner');
  var permissions = ndAllPages_(function (token) {
    var options = {pageSize: 100, fields: 'nextPageToken,permissions(id,type,role,emailAddress)'};
    if (token) options.pageToken = token;
    var page = Drive.Permissions.list(file.id, options);
    return {items: page.permissions || [], nextPageToken: page.nextPageToken};
  });
  if (permissions.length !== 1 || permissions[0].type !== 'user' || permissions[0].role !== 'owner' || permissions[0].emailAddress !== cfg.owner) throw new Error('sharing');
}

function ndFolder_(cfg) {
  var folder = ndFile_(cfg.folderId);
  if (folder.schema !== ND_SCHEMA || folder.kind !== 'requests' || folder.mimeType !== 'application/vnd.google-apps.folder' || folder.trashed) throw new Error('folder');
  ndPrivate_(folder, cfg);
}

function ndAssertRequest_(file, cfg) {
  if (file.schema !== ND_SCHEMA || file.kind !== 'request' || file.mimeType !== 'application/vnd.google-apps.spreadsheet' || file.parents.length !== 1 || file.parents[0] !== cfg.folderId || !ND_UUID.test(file.requestId || '') || !['writing', 'complete'].includes(file.state) || !Number.isInteger(file.issued) || !Number.isInteger(file.expires) || file.expires - file.issued < 60 || file.expires - file.issued > 86400 || !/^\d{4}-\d{2}-\d{2}T/.test(file.timestamp || '') || !/^[A-Za-z0-9_-]{43}$/.test(file.hash || '')) throw new Error('scope');
  ndPrivate_(file, cfg);
}

function ndList_(cfg, requestId, activeOnly) {
  // Configured IDs and canonical UUIDs are validated before building a query.
  if (!/^[A-Za-z0-9_-]+$/.test(cfg.folderId) || (requestId && !ND_UUID.test(requestId))) throw new Error('scope');
  var q = "'" + cfg.folderId + "' in parents and appProperties has { key='nd_schema' and value='" + ND_SCHEMA + "' } and appProperties has { key='nd_kind' and value='request' }";
  if (requestId) q += " and appProperties has { key='request_id' and value='" + requestId + "' }";
  if (activeOnly) q += ' and trashed = false';
  return ndAllPages_(function (token) {
    var options = {q: q, spaces: 'drive', pageSize: 100, fields: 'nextPageToken,incompleteSearch,files(id)'};
    if (token) options.pageToken = token;
    var page = Drive.Files.list(options);
    return {items: page.files || [], nextPageToken: page.nextPageToken, incompleteSearch: page.incompleteSearch};
  }).map(function (f) { return ndFile_(f.id); });
}

function ndOpStore_(cfg) {
  return {
    get: function (id) { var raw = cfg.properties.getProperty('ND_OP_' + id); return raw ? JSON.parse(raw) : null; },
    put: function (id, op) {
      if (!ND_UUID.test(id)) throw new Error('scope');
      var key = 'ND_OP_' + id, all = cfg.properties.getProperties();
      if (!Object.prototype.hasOwnProperty.call(all, key) && Object.keys(all).filter(function (k) { return k.indexOf('ND_OP_') === 0; }).length >= 100) throw new Error('operations limit');
      cfg.properties.setProperty(key, JSON.stringify(op));
    },
    remove: function (id) { cfg.properties.deleteProperty('ND_OP_' + id); }
  };
}

function ndSummaryFile_(cfg) {
  var f = ndFile_(cfg.summaryId);
  if (f.schema !== ND_SCHEMA || f.kind !== 'summary' || f.mimeType !== 'application/vnd.google-apps.spreadsheet' || f.trashed) throw new Error('summary');
  ndPrivate_(f, cfg);
}

function ndInvalidateSummary_(cfg) {
  ndSummaryFile_(cfg);
  Sheets.Spreadsheets.Values.update({values: [['nodina-counts-v1', 'unavailable', new Date().toISOString(), Utilities.getUuid()]]}, cfg.summaryId, 'Snapshot!A2:D2', {valueInputOption: 'RAW'});
}

function ndCells_(values) {
  return values.map(function (row) { return {values: row.map(function (v) { return {userEnteredValue: typeof v === 'number' ? {numberValue: v} : {stringValue: String(v)}}; })}; });
}

function ndInitializeSheets_(id, secondTab) {
  var current = Sheets.Spreadsheets.get(id, {fields: 'sheets.properties'}).sheets || [];
  if (current.length !== 1) throw new Error('new spreadsheet');
  Sheets.Spreadsheets.batchUpdate({requests: [
    {updateSpreadsheetProperties: {properties: {locale: 'fr_FR', timeZone: 'Europe/Paris'}, fields: 'locale,timeZone'}},
    {updateSheetProperties: {properties: {sheetId: current[0].properties.sheetId, title: secondTab === 'Conservation' ? 'Contact' : 'Snapshot', gridProperties: {rowCount: secondTab === 'Conservation' ? 10 : 3, columnCount: secondTab === 'Conservation' ? 17 : 4, frozenRowCount: 1, hideGridlines: true}}, fields: 'title,gridProperties'}},
    {addSheet: {properties: {sheetId: 20261006, title: secondTab, gridProperties: {rowCount: secondTab === 'Conservation' ? 10 : 10001, columnCount: secondTab === 'Conservation' ? 9 : 3, frozenRowCount: 1, hideGridlines: true}}}}
  ]}, id);
}

function ndDependencies_(cfg) {
  ndFolder_(cfg);
  var ops = ndOpStore_(cfg);
  return {
    crypto: ndCrypto_(cfg), now: function () { return Date.now(); }, getOp: ops.get, putOp: ops.put, removeOp: ops.remove,
    invalidate: function () { ndInvalidateSummary_(cfg); },
    find: function (id) { return ndList_(cfg, id, false); }, getFile: ndFile_,
    assertFile: function (f, claim, hash) { ndAssertRequest_(f, cfg); if (f.requestId !== claim.id || f.hash !== hash || f.expires !== claim.expires || f.issued !== claim.issued) throw new Error('mismatch'); },
    assertRetirementFile: function (f) { ndAssertRequest_(f, cfg); },
    create: function (m) {
      var f = Drive.Files.create({name: 'NODINA — Demande — ' + m.id, mimeType: 'application/vnd.google-apps.spreadsheet', parents: [cfg.folderId], appProperties: {nd_schema: ND_SCHEMA, nd_kind: 'request', request_id: m.id, payload_hash: m.hash, receipt_state: 'writing', received_at: m.timestamp, issued: String(m.issued), expires: String(m.expires)}}, null, {ignoreDefaultVisibility: true, fields: 'id'});
      return ndFile_(f.id);
    },
    write: function (f, row) {
      var tabs = Sheets.Spreadsheets.get(f.id, {fields: 'sheets.properties'}).sheets || [];
      if (tabs.length === 1 && tabs[0].properties.title !== 'Contact') ndInitializeSheets_(f.id, 'Conservation');
      // Recheck access immediately before writing any visitor fields.
      ndFolder_(cfg); ndPrivate_(ndFile_(f.id), cfg);
      // Always resume to exactly the same strings; no USER_ENTERED parsing.
      Sheets.Spreadsheets.Values.batchUpdate({valueInputOption: 'RAW', data: [
        {range: 'Contact!A1:Q2', values: [ND_HEADERS, row]},
        {range: 'Conservation!A1:I2', values: [['reference', 'statut', 'dernier_echange', 'echeance', 'responsable', 'classeur', 'messagerie', 'autres_copies', 'exception'], [f.requestId, 'À examiner', '', '', cfg.owner, 'À vérifier', 'À vérifier', 'À vérifier', '']]}
      ]}, f.id);
      // Calendar-based due date; fr_FR USER_ENTERED formulas require semicolons.
      Sheets.Spreadsheets.Values.update({values: [['=IF(AND(B2="Sans suite";ISNUMBER(C2);C2>0;C2<=TODAY());EDATE(C2;12);"")']]}, f.id, 'Conservation!D2', {valueInputOption: 'USER_ENTERED'});
    },
    readRow: function (f) {
      var values = Sheets.Spreadsheets.Values.get(f.id, 'Contact!A1:Q2', {valueRenderOption: 'UNFORMATTED_VALUE'}).values || [];
      if (JSON.stringify(values[0]) !== JSON.stringify(ND_HEADERS)) throw new Error('headers');
      return (values[1] || []).map(String);
    },
    complete: function (f) { Drive.Files.update({appProperties: {receipt_state: 'complete'}}, f.id, null, {fields: 'id'}); },
    readStatus: function (f) { var v = Sheets.Spreadsheets.Values.get(f.id, 'Contact!Q2', {valueRenderOption: 'UNFORMATTED_VALUE'}).values || []; return v[0] && v[0][0]; },
    mark: function (f, status) { Sheets.Spreadsheets.Values.update({values: [[status]]}, f.id, 'Contact!Q2', {valueInputOption: 'RAW'}); },
    canNotify: function () { return MailApp.getRemainingDailyQuota() > 0; },
    notify: function (message) { MailApp.sendEmail({to: cfg.recipient, subject: message.subject, body: message.body}); },
    isRetired: function (id) { var op = ops.get(id); return !!op && op.kind === 'retired'; },
    readMetrics: function (f) { var v = Sheets.Spreadsheets.Values.get(f.id, 'Contact!A1:E2', {valueRenderOption: 'UNFORMATTED_VALUE'}).values || []; if (JSON.stringify(v[0]) !== JSON.stringify(ND_HEADERS.slice(0, 5)) || !v[1] || v[1][1] !== f.requestId) throw new Error('metrics'); return {timestamp: v[1][0], ref: v[1][2], name: v[1][4]}; },
    day: function (timestamp) { return Utilities.formatDate(new Date(timestamp), 'Europe/Paris', 'yyyy-MM-dd'); }
  };
}

function ndInitializeProduction_() {
  // Editor only. Initialize a separate private production store after review.
  var cfg = ndSettings_(false), p = cfg.properties;
  if (p.getProperty('ND_SETUP_PENDING')) throw new Error('setup uncertain: reconcile in Drive before retry');
  if (!cfg.key) p.setProperty('ND_SIGNING_KEY', [Utilities.getUuid(), Utilities.getUuid(), Utilities.getUuid(), Utilities.getUuid()].join(''));
  function create(kind, mimeType, title, property) {
    if (p.getProperty(property)) return;
    p.setProperty('ND_SETUP_PENDING', kind);
    var f = Drive.Files.create({name: title, mimeType: mimeType, appProperties: {nd_schema: ND_SCHEMA, nd_kind: kind}}, null, {ignoreDefaultVisibility: true, fields: 'id'});
    p.setProperty(property, f.id);
    ndPrivate_(ndFile_(f.id), cfg);
    if (kind === 'summary') {
      ndInitializeSheets_(f.id, 'Counts');
      Sheets.Spreadsheets.Values.update({values: [['schema', 'status', 'computed_at', 'generation'], ['nodina-counts-v1', 'unavailable', new Date().toISOString(), Utilities.getUuid()]]}, f.id, 'Snapshot!A1:D2', {valueInputOption: 'RAW'});
      Sheets.Spreadsheets.Values.update({values: [['day', 'ref', 'leads']]}, f.id, 'Counts!A1:C1', {valueInputOption: 'RAW'});
    }
    p.deleteProperty('ND_SETUP_PENDING');
  }
  create('requests', 'application/vnd.google-apps.folder', 'NODINA — Dossiers individuels', 'ND_FOLDER_ID');
  create('summary', 'application/vnd.google-apps.spreadsheet', 'NODINA — Synthèse des comptes', 'ND_SUMMARY_ID');
  ndFolder_(ndSettings_(true));
  return {ready: true}; // Do not print configuration, signing key or file inventory.
}

function ndPrepareRetirement_() {
  // Editor only; prepares a tombstone, NEVER deletes. IDs explicitly set by JD.
  var cfg = ndSettings_(true), id = cfg.properties.getProperty('ND_REVIEW_FILE_ID'), ref = cfg.properties.getProperty('ND_REVIEW_REQUEST_ID');
  var lock = LockService.getScriptLock(); if (!lock.tryLock(10000)) throw new Error('busy');
  try { return ndRetire_(ndFile_(id), ref, ndDependencies_(cfg)); } finally { lock.releaseLock(); }
}

function ndClearExpiredRetirements_() {
  var cfg = ndSettings_(true), lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) throw new Error('busy');
  try {
    var all = cfg.properties.getProperties(), removed = 0;
    Object.keys(all).filter(function (key) { return key.indexOf('ND_OP_') === 0; }).forEach(function (key) {
      var op = JSON.parse(all[key]);
      if (op.kind === 'retired' && Number.isInteger(op.expires) && op.expires * 1000 <= Date.now()) { cfg.properties.deleteProperty(key); removed++; }
    });
    return {removed: removed};
  } finally { lock.releaseLock(); }
}

function ndRebuildSummary_() {
  var cfg = ndSettings_(true), lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) throw new Error('busy');
  try {
    ndInvalidateSummary_(cfg);
    var d = ndDependencies_(cfg), files = ndList_(cfg, null, true);
    var signature = function (list) { return JSON.stringify(list.map(function (f) { return [f.id, f.modifiedTime]; }).sort()); };
    var before = signature(files), counts = ndCounts_(files, d);
    if (before !== signature(ndList_(cfg, null, true))) throw new Error('snapshot changed');
    if (counts.length > 10000) throw new Error('summary limit');
    var sheets = Sheets.Spreadsheets.get(cfg.summaryId, {fields: 'sheets.properties'}).sheets;
    var snapshot = sheets.find(function (s) { return s.properties.title === 'Snapshot'; }), table = sheets.find(function (s) { return s.properties.title === 'Counts'; });
    if (!snapshot || !table) throw new Error('summary schema');
    Sheets.Spreadsheets.batchUpdate({requests: [
      {repeatCell: {range: {sheetId: table.properties.sheetId}, cell: {}, fields: 'userEnteredValue'}},
      {updateCells: {start: {sheetId: table.properties.sheetId, rowIndex: 0, columnIndex: 0}, rows: ndCells_([['day', 'ref', 'leads']].concat(counts)), fields: 'userEnteredValue'}},
      {updateCells: {start: {sheetId: snapshot.properties.sheetId, rowIndex: 1, columnIndex: 0}, rows: ndCells_([['nodina-counts-v1', 'complete', new Date().toISOString(), Utilities.getUuid()]]), fields: 'userEnteredValue'}}
    ]}, cfg.summaryId);
    return {complete: true, buckets: counts.length};
  } finally { lock.releaseLock(); }
}

function ndEscape_(value) {
  return String(value).replace(/[&<>"']/g, function (c) { return {'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]; });
}

function ndJson_(value) { return ContentService.createTextOutput(JSON.stringify(value)).setMimeType(ContentService.MimeType.JSON); }

function ndResult_(result, params) {
  // Whitelist the public response: never return an adapter error or file ID.
  var safe = result.ok === true ? {ok: true} : {ok: false, code: result.code === 'invalid' ? 'invalid' : 'unavailable'};
  if (params.response_format === 'json') return ndJson_(safe);
  var fr = params.locale !== 'en';
  var title = safe.ok ? (fr ? 'Demande enregistrée' : 'Inquiry recorded') : (fr ? 'Envoi non confirmé' : 'Submission not confirmed');
  var text = safe.ok ? (fr ? 'Nous reviendrons vers vous pour préciser la suite.' : 'We will get back to you to discuss next steps.') : (fr ? 'Revenez au formulaire, vérifiez les champs et réessayez.' : 'Return to the form, check the fields and try again.');
  return HtmlService.createHtmlOutput('<!doctype html><html lang="' + (fr ? 'fr' : 'en') + '"><head><meta name="robots" content="noindex,nofollow"><title>' + title + '</title></head><body><main><h1>' + title + '</h1><p>' + text + '</p><a target="_top" href="https://nodina.com/' + (fr ? 'fr' : 'en') + '/contact/">NODINA</a></main></body></html>').setTitle(title);
}

function ndHostedForm_(locale, receipt, endpoint) {
  // Workspace and standard service URLs differ; dev is the private editor preview.
  if (!/^https:\/\/script\.google\.com\/(?:macros\/s|a\/(?:macros\/nodina\.com\/s|nodina\.com\/macros\/s))\/[A-Za-z0-9_-]+\/(?:exec|dev)$/.test(endpoint || '')) throw new Error('endpoint');
  var fr = locale === 'fr', labels = fr ? ['Nom', 'E-mail professionnel', 'Organisation', 'Besoin', 'Contexte du projet', 'Calendrier envisagé', 'Envoyer'] : ['Name', 'Work email', 'Organization', 'Need', 'Project context', 'Expected timing', 'Send'];
  function field(name, label, extra) { return '<p><label>' + label + '<br><input name="' + name + '" ' + extra + '></label></p>'; }
  var html = '<!doctype html><html lang="' + locale + '"><head><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width"><title>NODINA Contact</title></head><body><main><h1>NODINA Contact</h1><form method="post" target="_top" action="' + ndEscape_(endpoint) + '">';
  // Production profile; never prefill personal information.
  html += '<p>' + (fr ? 'Ces informations servent à traiter votre demande. Ne transmettez pas de données confidentielles.' : 'This information is used to handle your inquiry. Do not include confidential information.') + '</p>';
  html += field('name', labels[0], 'required maxlength="120" autocomplete="name"');
  html += field('email', labels[1], 'type="email" required maxlength="254" autocomplete="email"');
  html += field('organization', labels[2], 'required maxlength="160" autocomplete="organization"');
  html += '<p><label>' + labels[3] + '<br><select name="offer"><option value="unknown">—</option><option value="teams">Teams</option><option value="systems">Systems</option><option value="combined">Teams + Systems</option></select></label></p>';
  html += '<p><label>' + labels[4] + '<br><textarea name="project" required minlength="10" maxlength="5000" rows="5"></textarea></label></p>';
  html += field('timing', labels[5], 'maxlength="200" autocomplete="off"');
  [['locale', locale], ['request_id', receipt.request_id], ['receipt_token', receipt.token], ['consent_version', 'contact-v1'], ['ref', '/' + locale + '/contact/']].forEach(function (pair) { html += '<input type="hidden" name="' + pair[0] + '" value="' + ndEscape_(pair[1]) + '">'; });
  html += '<div hidden aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p><label><input type="checkbox" name="consent" value="yes" required>' + ndEscape_(ND_CONSENT[locale]) + '</label></p>';
  html += '<p><a target="_top" href="https://nodina.com/' + locale + '/' + (fr ? 'confidentialite' : 'privacy') + '/">' + (fr ? 'Utilisation de vos données et vos droits' : 'How your information is used and your rights') + '</a></p><p>' + (fr ? 'Vous pouvez retirer votre accord à tout moment : ' : 'You can withdraw your consent at any time: ') + '<a href="mailto:build@nodina.com">build@nodina.com</a>.</p>';
  return html + '<button type="submit">' + labels[6] + '</button></form></main></body></html>';
}

function doGet(event) {
  var p = event && event.parameter || {}, locale = p.locale === 'en' ? 'en' : 'fr';
  try {
    if (p.mode && p.mode !== 'token') return ndResult_({ok: false, code: 'invalid'}, p);
    var cfg = ndSettings_(true), receipt = ndIssue_(locale, Date.now(), cfg.ttl, ndCrypto_(cfg));
    if (p.mode === 'token') return ndJson_(receipt);
    return HtmlService.createHtmlOutput(ndHostedForm_(locale, receipt, ScriptApp.getService().getUrl())).setTitle('NODINA Contact');
  } catch (error) { return ndResult_({ok: false, code: 'unavailable'}, p); }
}

function doPost(event) {
  var p = event && event.parameter || {}, lock, acquired = false;
  try {
    if (!event || !Number.isFinite(event.contentLength) || event.contentLength <= 0 || event.contentLength > 40000 || (event.postData && event.postData.type && event.postData.type.split(';')[0] !== 'application/x-www-form-urlencoded')) return ndResult_({ok: false, code: 'invalid'}, p);
    if (event.parameters && Object.keys(event.parameters).some(function (key) { return event.parameters[key].length !== 1; })) return ndResult_({ok: false, code: 'invalid'}, p);
    var cfg = ndSettings_(true), validation = ndValidate_(p, Date.now(), ndCrypto_(cfg));
    if (!validation.ok) return ndResult_({ok: false, code: 'invalid'}, p);
    // Only receipt is routed. No action, file ID, recipient or admin parameters.
    lock = LockService.getScriptLock(); acquired = lock.tryLock(10000);
    if (!acquired) throw new Error('busy');
    // Revalidate time after waiting for the lock; an expired token cannot slip in.
    validation = ndValidate_(p, Date.now(), ndCrypto_(cfg));
    return ndResult_(ndRecord_(validation, ndDependencies_(cfg)), p);
  } catch (error) { return ndResult_({ok: false, code: 'unavailable'}, p); }
  finally { if (acquired) lock.releaseLock(); }
}
